# Generated by Django 2.0.2 on 2018-03-02 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='brand_svyaz',
            field=models.ForeignKey(default=663708, on_delete=django.db.models.deletion.CASCADE, to='demoapp.Brands'),
            preserve_default=False,
        ),
    ]
