# Generated by Django 2.0.2 on 2018-03-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_auto_20180302_1500'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
    ]
