# Generated by Django 2.0.2 on 2018-03-12 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_auto_20180309_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand_svyaz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.Brand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='colors_mtom',
            field=models.ManyToManyField(related_name='cars', to='demoapp.Color'),
        ),
    ]
