# Generated by Django 2.0.2 on 2018-03-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0007_auto_20180312_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
    ]
