# Generated by Django 2.0.2 on 2018-03-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0009_remove_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
