# Generated by Django 2.0.2 on 2018-03-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0011_remove_car_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brand_svyaz',
            new_name='brand',
        ),
    ]
