# Generated by Django 2.0.2 on 2018-03-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0012_auto_20180314_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='colors_mtom',
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ManyToManyField(related_name='cars', to='demoapp.Color'),
        ),
    ]
