# Generated by Django 2.0.2 on 2018-03-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20180328_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='slug',
            field=models.SlugField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
